#!/bin/sh

# Path to this script

# Message text handler function
# Simple function to keep code clean and pass mneumonic code and arguments to message-text script


# 1. Installation with previous DSM-7 installation somewhere in statis?  (install that volume if found)



    # Instructions for user
. $(dirname $0)/installer
$(basename $0) > $SYNOPKG_TEMP_LOGFILE
notify-send "pi" "set-up"


# 5. No news is good news



